# Site
title:              TIGER
bio:                'Can Haz Bio'
description:        "Teaching Innovation, Graciousness, and Engineering through Robotics"
locale:             en_US
baseurl: "/TIGER" # the subpath of your site, e.g. /blog
url: "team900.org" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default



# personal
location:           Durham, NC
phone:
email:              support@team900.org

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 10
paginate_path: "/labs/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

handbook: https://drive.google.com/file/d/0B7SC9BMzdll7dU5WYlBEdjVGWlk/view
